[package]
name = "boxxy"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/queer/boxxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bat = { version = "0.23.0", default-features = false, features = [
  "atty",
  "regex-onig",
] }
byteorder = "1.5.0"
cfg-if = "1.0.0"
clap = { version = "4.5.11", features = ["derive"] }
color-eyre = { version = "0.6.3", features = ["issue-url"] }
config = "0.14.0"
ctrlc = "3.4.4"
daemonize = "0.5.0"
dirs = "5.0.1"
dotenv = "0.15.0"
dotenv-parser = "0.1.3"
eyre = "0.6.12"
grep = "0.3.1"
haikunator = "0.1.2"
lazy_static = "1.5.0"
libc = "0.2.155"
log = "0.4.22"
nix = { version = "0.29.0", features = [
  "process",
  "user",
  "mount",
  "sched",
  "ptrace",
  "signal",
  "fs",
] }
owo-colors = { version = "4.0.0", features = [
  "supports-color",
  "supports-colors",
] }
pretty_env_logger = "0.5.0"
regex = "1.10.5"
rlimit = "0.10.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"
shellexpand = "3.1.0"
strum = { version = "0.26.3", features = ["derive"] }
syscall-numbers = "3.1.1"
which = "6.0.1"

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
