name: "Run cargo audit"
on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    paths:
    - "**.rs"
    - "**.toml"
  pull_request:
    branches:
    - "main"
    paths:
    - "**.rs"
    - "**.toml"

jobs:
  run-cargo-audit:
    strategy:
      matrix:
        version: ["stable", "1.88", "nightly"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - name: install Rust ${{ matrix.version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "${{ matrix.version }}"
    - name: rust audit
      uses: rustsec/audit-check@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

