name: "Build and Publish Rust Binaries"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: "actions/checkout@v4"
          
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.BUILD_TARGET }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --${{ matrix.BUILD_TARGET }}
      
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io --password-stdin -u ${{ github.actor }}

      - name: Push binary
        run: |
          oras push ghcr.io/${{ github.repository_owner }}/boxxy:${GITHUB_REF#refs/tags/} \
            target/release/boxxy



