name: "Run clippy lints"
on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    paths:
    - "**.rs"
  pull_request:
    branches:
    - "main"
    paths:
    - "**.rs"

jobs:
  run-clippy:
    strategy:
      matrix:
        version: ["stable", "1.88", "nightly"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
      
    - name: install Rust ${{ matrix.version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "${{ matrix.version }}"
        components: "clippy"

    - uses: "Swatinem/rust-cache@v2"
      with:
        key: "clippy"
        
    - name: "Run clippy"
      run: "cargo clippy --all-targets --all-features -- -D warnings"
