name: "Build docs"
on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    paths:
    - "**.rs"
  pull_request:
    branches:
    - "main"
    paths:
    - "**.rs"

jobs:
  docs:
    strategy:
      matrix:
        version: ["stable", "1.88", "nightly"]
    if: ${{ github.actor != 'dependabot' }}
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
      
    - name: install Rust ${{ matrix.version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "${{ matrix.version }}"

    - uses: "Swatinem/rust-cache@v2"
      with:
        key: "doc"

    - name: "Run cargo doc"
      run: "cargo doc --workspace --all-features --examples --no-deps --locked"
