name: "Run all tests"
on:
  workflow_dispatch:
  push:
    branches:
    - "main"
    paths:
    - "**.rs"
  pull_request:
    branches:
    - "main"
    paths:
    - "**.rs"

jobs:
  run-tests:
    strategy:
      matrix:
        version: ["stable"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
      
    - name: install Rust ${{ matrix.version }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: "${{ matrix.version }}"

    - uses: "Swatinem/rust-cache@v2"
      with:
        key: "tests"
        
    - name: "Run tests"
      run: "cargo test"
